# Configuration file for Stroke Prediction Application

# Flask Configuration
FLASK_ENV = development
FLASK_DEBUG = True
SECRET_KEY = your-secret-key-here-change-in-production

# Server Configuration
HOST = 0.0.0.0
PORT = 5000

# Model Configuration
MODEL_PATH = best_model_knn.joblib
PREPROCESSOR_PATH = preprocessor.joblib

# CORS Configuration
CORS_ORIGINS = ["http://localhost:5000", "http://127.0.0.1:5000"]

# Logging
LOG_LEVEL = INFO
